# Generated by Django 5.2.7 on 2025-10-30 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GerenciadoraRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da GR')),
                ('validade_checklist', models.IntegerField(choices=[(30, '30 dias'), (60, '60 dias'), (90, '90 dias')], verbose_name='Validade do Checklist')),
            ],
        ),
        migrations.CreateModel(
            name='RegraEmbarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rotograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_titulo', models.CharField(max_length=255, verbose_name='Nome/Título')),
                ('origem', models.CharField(max_length=150)),
                ('destino', models.CharField(max_length=150)),
                ('arquivo_pdf', models.FileField(upload_to='rotogramas_pdfs/', verbose_name='Arquivo PDF do Rotograma')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('categoria', models.CharField(choices=[('Frota', 'Frota'), ('Agregado', 'Agregado')], max_length=10)),
                ('tipo', models.CharField(choices=[('Cavalo Mecânico', 'Cavalo Mecânico'), ('Carreta', 'Carreta')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PGR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_cliente', models.CharField(max_length=255, verbose_name='Título do PGR (Cliente)')),
                ('validade', models.DateField(verbose_name='Validade do PGR')),
                ('gerente_conta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Gerente de Conta')),
                ('contato_gc', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone de Contato do GC')),
                ('email_gc', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do GC')),
                ('tipo_seguro', models.CharField(choices=[('Próprio', 'Próprio'), ('DDR', 'DDR')], max_length=10, verbose_name='Tipo de Seguro')),
                ('arquivo_pdf', models.FileField(upload_to='pgr_pdfs/', verbose_name='Arquivo PDF do PGR')),
                ('responsavel_cadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pgrs_cadastrados', to=settings.AUTH_USER_MODEL)),
                ('regras_embarque', models.ManyToManyField(blank=True, to='APP.regraembarque')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Iniciada', 'Iniciada'), ('Finalizada', 'Finalizada')], default='Pendente', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='APP.tarefa')),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprovado', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3)),
                ('data_aprovacao', models.DateField(blank=True, null=True, verbose_name='Data de Aprovação/Realização')),
                ('data_fim_validade', models.DateField(blank=True, null=True, verbose_name='Data de Fim da Validade Manual')),
                ('motivo_reprovacao', models.TextField(blank=True, null=True)),
                ('ultimo_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_alterados', to=settings.AUTH_USER_MODEL)),
                ('gerenciadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.gerenciadorarisco', verbose_name='GR')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.veiculo')),
            ],
            options={
                'unique_together': {('veiculo', 'gerenciadora')},
            },
        ),
    ]
