# Generated by Django 5.2.7 on 2025-10-31 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguradora', models.CharField(max_length=100)),
                ('tipo_apolice', models.CharField(max_length=100, verbose_name='Tipo de Apólice')),
                ('corretora', models.CharField(max_length=100)),
                ('corretor', models.CharField(max_length=100)),
                ('contato_corretor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone de Contato')),
                ('email_corretor', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do Corretor')),
                ('vigencia', models.DateField(verbose_name='Vigência do Seguro')),
                ('descricao_resumo', models.TextField(blank=True, null=True, verbose_name='Descrição/Resumo')),
                ('apolice_pdf', models.FileField(upload_to='seguros/apolices/', verbose_name='Upload da Apólice (PDF)')),
                ('certificado_pdf', models.FileField(upload_to='seguros/certificados/', verbose_name='Upload do Certificado (PDF)')),
                ('responsavel_cadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguros_cadastrados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
