# Generated by Django 5.2.7 on 2025-10-31 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_seguro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sinistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_sinistro', models.DateField(verbose_name='Data do Sinistro')),
                ('hora_sinistro', models.TimeField(verbose_name='Hora do Sinistro')),
                ('seguradora_responsavel', models.CharField(max_length=100, verbose_name='Seguradora Responsável')),
                ('status', models.CharField(choices=[('Em andamento', 'Em andamento'), ('Finalizado', 'Finalizado')], default='Em andamento', max_length=20)),
                ('detalhes', models.TextField(verbose_name='Detalhes')),
                ('responsavel_cadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sinistros_cadastrados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
