# Generated by Django 5.2.7 on 2025-10-31 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_sinistro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VeiculoAssegurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguradora', models.CharField(max_length=100)),
                ('vigencia', models.DateField(verbose_name='Vigência')),
                ('placa', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('ano_fabricacao', models.IntegerField(verbose_name='Ano de Fabricação')),
                ('ano_modelo', models.IntegerField(verbose_name='Ano do Modelo')),
                ('cobertura', models.CharField(choices=[('Total', 'Total'), ('Apenas Terceiros', 'Apenas Terceiros')], default='Total', max_length=20)),
                ('valor_fipe_percent', models.IntegerField(verbose_name='Valor FIPE (%)')),
                ('franquia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('danos_materiais', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Danos Materiais')),
                ('danos_corporais', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Danos Corporais')),
                ('danos_morais', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Danos Morais')),
                ('app_morte', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='APP Morte')),
                ('app_invalidez', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='APP Invalidez')),
                ('assistencia_km', models.IntegerField(verbose_name='Reboque/Assistência 24h (KM)')),
                ('carro_reserva_dias', models.IntegerField(verbose_name='Carro Reserva (dias)')),
                ('cobertura_vidros', models.BooleanField(default=False, verbose_name='Cobertura extra para vidros')),
                ('responsavel_cadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculos_assegurados_cadastrados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
