# Generated by Django 5.2.7 on 2025-10-31 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_veiculoassegurado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicotarefa',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='tarefa',
            options={'ordering': ['-criado_em']},
        ),
        migrations.CreateModel(
            name='SecurityTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Iniciada', 'Iniciada'), ('Finalizada', 'Finalizada')], default='Pendente', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarefa de Security',
                'verbose_name_plural': 'Tarefas de Security',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SecurityHistoricoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='APP.securitytarefa')),
            ],
            options={
                'verbose_name': 'Histórico de Tarefa de Security',
                'verbose_name_plural': 'Históricos de Tarefas de Security',
                'ordering': ['timestamp'],
            },
        ),
    ]
