# Generated by Django 5.2.7 on 2025-11-02 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_alter_historicotarefa_options_alter_tarefa_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoQSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificado', models.CharField(max_length=255, verbose_name='Certificado')),
                ('orgao_competente', models.CharField(max_length=255, verbose_name='Órgão Competente')),
                ('link_orgao', models.URLField(blank=True, max_length=255, null=True, verbose_name='Link do Órgão')),
                ('validade', models.DateField(verbose_name='Validade')),
                ('arquivo_pdf', models.FileField(upload_to='qsms/certificados_pdf/', verbose_name='Upload de Certificado PDF')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('responsavel_cadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_qsms_cadastrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificado QSMS',
                'verbose_name_plural': 'Certificados QSMS',
                'ordering': ['validade'],
            },
        ),
    ]
