# Generated by Django 5.2.7 on 2025-11-02 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_certificadoqsms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaQSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Treinamento', 'Treinamento'), ('Evento', 'Evento')], default='Treinamento', max_length=20)),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('data_evento', models.DateField(verbose_name='Data do Evento')),
                ('hora_evento', models.TimeField(verbose_name='Hora do Evento')),
                ('detalhes', models.TextField(blank=True, null=True, verbose_name='Detalhes')),
                ('responsavel_cadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_qsms_cadastrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento da Agenda QSMS',
                'verbose_name_plural': 'Eventos da Agenda QSMS',
                'ordering': ['data_evento', 'hora_evento'],
            },
        ),
    ]
