# Generated by Django 5.2.7 on 2025-11-02 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_qsmstarefa_qsmshistoricotarefa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoDiverso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Documento')),
                ('arquivo_pdf', models.FileField(upload_to='arquivos_diversos/', verbose_name='Upload de Arquivo PDF')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('responsavel_cadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivos_diversos_cadastrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arquivo Diverso',
                'verbose_name_plural': 'Arquivos Diversos',
                'ordering': ['titulo'],
            },
        ),
    ]
