# Generated by Django 5.2.7 on 2025-11-10 14:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0009_arquivodiverso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CondutorBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='O CPF deve estar no formato XXX.XXX.XXX-XX.', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF')),
                ('data_pesquisa', models.DateField(verbose_name='Data da Pesquisa')),
                ('motivo_reprovacao', models.TextField(verbose_name='Motivo da Reprovação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('responsavel_cadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condutores_blacklist_cadastrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Condutor (Blacklist)',
                'verbose_name_plural': 'Condutores (Blacklist)',
                'ordering': ['nome_completo'],
            },
        ),
    ]
