# Generated by Django 6.0 on 2025-12-30 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0010_condutorblacklist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaFarmaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Treinamento', 'Treinamento'), ('Evento', 'Evento')], default='Treinamento', max_length=20)),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('data_evento', models.DateField(verbose_name='Data do Evento')),
                ('hora_evento', models.TimeField(verbose_name='Hora do Evento')),
                ('detalhes', models.TextField(blank=True, null=True, verbose_name='Detalhes')),
                ('responsavel_cadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_farmaco_cadastrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento da Agenda Fármaco',
                'verbose_name_plural': 'Eventos da Agenda Fármaco',
                'ordering': ['data_evento', 'hora_evento'],
            },
        ),
        migrations.CreateModel(
            name='CertificadoFarmaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificado', models.CharField(max_length=255, verbose_name='Certificado')),
                ('orgao_competente', models.CharField(max_length=255, verbose_name='Órgão Competente')),
                ('link_orgao', models.URLField(blank=True, max_length=255, null=True, verbose_name='Link do Órgão')),
                ('validade', models.DateField(verbose_name='Validade')),
                ('arquivo_pdf', models.FileField(upload_to='farmaco/certificados_pdf/', verbose_name='Upload de Certificado PDF')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('responsavel_cadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_farmaco_cadastrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificado Fármaco',
                'verbose_name_plural': 'Certificados Fármaco',
                'ordering': ['validade'],
            },
        ),
        migrations.CreateModel(
            name='FarmacoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Iniciada', 'Iniciada'), ('Finalizada', 'Finalizada')], default='Pendente', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarefa de Fármaco',
                'verbose_name_plural': 'Tarefas de Fármaco',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FarmacoHistoricoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='APP.farmacotarefa')),
            ],
            options={
                'verbose_name': 'Histórico de Tarefa de Fármaco',
                'verbose_name_plural': 'Históricos de Tarefas de Fármaco',
                'ordering': ['timestamp'],
            },
        ),
    ]
