# Generated by Django 6.0 on 2025-12-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0011_agendafarmaco_certificadofarmaco_farmacotarefa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleAttachmentPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Permissão de Anexo',
                'verbose_name_plural': 'Permissões de Anexos',
                'permissions': (('view_gr_attachments', 'Pode visualizar anexos do GR (PGRs, Rotogramas)'), ('view_security_attachments', 'Pode visualizar anexos do Security (Apólices, Certificados)'), ('view_qsms_attachments', 'Pode visualizar anexos do QSMS (Certificados)'), ('view_farmaco_attachments', 'Pode visualizar anexos do Fármaco (Certificados)')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
