# Generated by Django 5.2.7 on 2026-01-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0012_moduleattachmentpermissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModulePermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "PermissÃ£o de MÃ³dulo",
                "verbose_name_plural": "PermissÃµes de MÃ³dulos",
                "permissions": (
                    ("view_gr_module", "Pode visualizar mÃ³dulo GR"),
                    (
                        "view_gr_attachments",
                        "Pode visualizar anexos do GR (PGRs, Rotogramas)",
                    ),
                    ("view_security_module", "Pode visualizar mÃ³dulo Security"),
                    (
                        "view_security_attachments",
                        "Pode visualizar anexos do Security (ApÃ³lices, Certificados)",
                    ),
                    ("view_qsms_module", "Pode visualizar mÃ³dulo QSMS"),
                    (
                        "view_qsms_attachments",
                        "Pode visualizar anexos do QSMS (Certificados)",
                    ),
                    ("view_farmaco_module", "Pode visualizar mÃ³dulo FÃ¡rmaco"),
                    (
                        "view_farmaco_attachments",
                        "Pode visualizar anexos do FÃ¡rmaco (Certificados)",
                    ),
                    (
                        "view_arquivosdiversos_module",
                        "Pode visualizar mÃ³dulo Arquivos Diversos",
                    ),
                    (
                        "view_all_arquivodiverso",
                        "Pode visualizar todos os arquivos diversos",
                    ),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.DeleteModel(
            name="ModuleAttachmentPermissions",
        ),
        migrations.AlterModelOptions(
            name="agendafarmaco",
            options={
                "ordering": ["data_evento", "hora_evento"],
                "verbose_name": "Evento da Agenda FÃ¡rmaco",
                "verbose_name_plural": "Eventos da Agenda FÃ¡rmaco",
            },
        ),
        migrations.AlterModelOptions(
            name="certificadofarmaco",
            options={
                "ordering": ["validade"],
                "verbose_name": "Certificado FÃ¡rmaco",
                "verbose_name_plural": "Certificados FÃ¡rmaco",
            },
        ),
        migrations.AlterModelOptions(
            name="farmacohistoricotarefa",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "HistÃ³rico de Tarefa de FÃ¡rmaco",
                "verbose_name_plural": "HistÃ³ricos de Tarefas de FÃ¡rmaco",
            },
        ),
        migrations.AlterModelOptions(
            name="farmacotarefa",
            options={
                "ordering": ["-criado_em"],
                "verbose_name": "Tarefa de FÃ¡rmaco",
                "verbose_name_plural": "Tarefas de FÃ¡rmaco",
            },
        ),
        migrations.AlterModelOptions(
            name="qsmshistoricotarefa",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "HistÃ³rico de Tarefa de QSMS",
                "verbose_name_plural": "HistÃ³ricos de Tarefas de QSMS",
            },
        ),
        migrations.AlterModelOptions(
            name="securityhistoricotarefa",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "HistÃ³rico de Tarefa de Security",
                "verbose_name_plural": "HistÃ³ricos de Tarefas de Security",
            },
        ),
        migrations.AlterField(
            model_name="arquivodiverso",
            name="descricao",
            field=models.TextField(
                blank=True, null=True, verbose_name="DescriÃ§Ã£o do Documento"
            ),
        ),
        migrations.AlterField(
            model_name="arquivodiverso",
            name="titulo",
            field=models.CharField(max_length=255, verbose_name="TÃ\xadtulo"),
        ),
        migrations.AlterField(
            model_name="certificadofarmaco",
            name="descricao",
            field=models.TextField(blank=True, null=True, verbose_name="DescriÃ§Ã£o"),
        ),
        migrations.AlterField(
            model_name="certificadofarmaco",
            name="link_orgao",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="Link do Ã“rgÃ£o"
            ),
        ),
        migrations.AlterField(
            model_name="certificadofarmaco",
            name="orgao_competente",
            field=models.CharField(max_length=255, verbose_name="Ã“rgÃ£o Competente"),
        ),
        migrations.AlterField(
            model_name="certificadoqsms",
            name="descricao",
            field=models.TextField(blank=True, null=True, verbose_name="DescriÃ§Ã£o"),
        ),
        migrations.AlterField(
            model_name="certificadoqsms",
            name="link_orgao",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="Link do Ã“rgÃ£o"
            ),
        ),
        migrations.AlterField(
            model_name="certificadoqsms",
            name="orgao_competente",
            field=models.CharField(max_length=255, verbose_name="Ã“rgÃ£o Competente"),
        ),
        migrations.AlterField(
            model_name="checklist",
            name="aprovado",
            field=models.CharField(
                choices=[("Sim", "Sim"), ("NÃ£o", "NÃ£o")], max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="checklist",
            name="data_aprovacao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de AprovaÃ§Ã£o/RealizaÃ§Ã£o"
            ),
        ),
        migrations.AlterField(
            model_name="condutorblacklist",
            name="motivo_reprovacao",
            field=models.TextField(verbose_name="Motivo da ReprovaÃ§Ã£o"),
        ),
        migrations.AlterField(
            model_name="pgr",
            name="tipo_seguro",
            field=models.CharField(
                choices=[("PrÃ³prio", "PrÃ³prio"), ("DDR", "DDR")],
                max_length=10,
                verbose_name="Tipo de Seguro",
            ),
        ),
        migrations.AlterField(
            model_name="pgr",
            name="titulo_cliente",
            field=models.CharField(
                max_length=255, verbose_name="TÃ\xadtulo do PGR (Cliente)"
            ),
        ),
        migrations.AlterField(
            model_name="rotograma",
            name="nome_titulo",
            field=models.CharField(max_length=255, verbose_name="Nome/TÃ\xadtulo"),
        ),
        migrations.AlterField(
            model_name="seguro",
            name="apolice_pdf",
            field=models.FileField(
                upload_to="seguros/apolices/", verbose_name="Upload da ApÃ³lice (PDF)"
            ),
        ),
        migrations.AlterField(
            model_name="seguro",
            name="descricao_resumo",
            field=models.TextField(
                blank=True, null=True, verbose_name="DescriÃ§Ã£o/Resumo"
            ),
        ),
        migrations.AlterField(
            model_name="seguro",
            name="tipo_apolice",
            field=models.CharField(max_length=100, verbose_name="Tipo de ApÃ³lice"),
        ),
        migrations.AlterField(
            model_name="seguro",
            name="vigencia",
            field=models.DateField(verbose_name="VigÃªncia do Seguro"),
        ),
        migrations.AlterField(
            model_name="sinistro",
            name="seguradora_responsavel",
            field=models.CharField(
                max_length=100, verbose_name="Seguradora ResponsÃ¡vel"
            ),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("Cavalo MecÃ¢nico", "Cavalo MecÃ¢nico"),
                    ("Carreta", "Carreta"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="veiculoassegurado",
            name="ano_fabricacao",
            field=models.IntegerField(verbose_name="Ano de FabricaÃ§Ã£o"),
        ),
        migrations.AlterField(
            model_name="veiculoassegurado",
            name="assistencia_km",
            field=models.IntegerField(verbose_name="Reboque/AssistÃªncia 24h (KM)"),
        ),
        migrations.AlterField(
            model_name="veiculoassegurado",
            name="vigencia",
            field=models.DateField(verbose_name="VigÃªncia"),
        ),
    ]
