# Generated by Django 5.2.7 on 2026-01-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0012_moduleattachmentpermissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModulePermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permissão de Módulo",
                "verbose_name_plural": "Permissões de Módulos",
                "permissions": (
                    ("view_gr_module", "Pode visualizar módulo GR"),
                    (
                        "view_gr_attachments",
                        "Pode visualizar anexos do GR (PGRs, Rotogramas)",
                    ),
                    ("view_security_module", "Pode visualizar módulo Security"),
                    (
                        "view_security_attachments",
                        "Pode visualizar anexos do Security (Apólices, Certificados)",
                    ),
                    ("view_qsms_module", "Pode visualizar módulo QSMS"),
                    (
                        "view_qsms_attachments",
                        "Pode visualizar anexos do QSMS (Certificados)",
                    ),
                    ("view_farmaco_module", "Pode visualizar módulo Fármaco"),
                    (
                        "view_farmaco_attachments",
                        "Pode visualizar anexos do Fármaco (Certificados)",
                    ),
                    (
                        "view_arquivosdiversos_module",
                        "Pode visualizar módulo Arquivos Diversos",
                    ),
                    (
                        "view_all_arquivodiverso",
                        "Pode visualizar todos os arquivos diversos",
                    ),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.DeleteModel(
            name="ModuleAttachmentPermissions",
        ),
        migrations.AlterModelOptions(
            name="agendafarmaco",
            options={
                "ordering": ["data_evento", "hora_evento"],
                "verbose_name": "Evento da Agenda Fármaco",
                "verbose_name_plural": "Eventos da Agenda Fármaco",
            },
        ),
        migrations.AlterModelOptions(
            name="certificadofarmaco",
            options={
                "ordering": ["validade"],
                "verbose_name": "Certificado Fármaco",
                "verbose_name_plural": "Certificados Fármaco",
            },
        ),
        migrations.AlterModelOptions(
            name="farmacohistoricotarefa",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "Histórico de Tarefa de Fármaco",
                "verbose_name_plural": "Históricos de Tarefas de Fármaco",
            },
        ),
        migrations.AlterModelOptions(
            name="farmacotarefa",
            options={
                "ordering": ["-criado_em"],
                "verbose_name": "Tarefa de Fármaco",
                "verbose_name_plural": "Tarefas de Fármaco",
            },
        ),
        migrations.AlterModelOptions(
            name="qsmshistoricotarefa",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "Histórico de Tarefa de QSMS",
                "verbose_name_plural": "Históricos de Tarefas de QSMS",
            },
        ),
        migrations.AlterModelOptions(
            name="securityhistoricotarefa",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "Histórico de Tarefa de Security",
                "verbose_name_plural": "Históricos de Tarefas de Security",
            },
        ),
        migrations.AlterField(
            model_name="arquivodiverso",
            name="descricao",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descrição do Documento"
            ),
        ),
        migrations.AlterField(
            model_name="arquivodiverso",
            name="titulo",
            field=models.CharField(max_length=255, verbose_name="TÃ\xadtulo"),
        ),
        migrations.AlterField(
            model_name="certificadofarmaco",
            name="descricao",
            field=models.TextField(blank=True, null=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="certificadofarmaco",
            name="link_orgao",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="Link do Órgão"
            ),
        ),
        migrations.AlterField(
            model_name="certificadofarmaco",
            name="orgao_competente",
            field=models.CharField(max_length=255, verbose_name="Órgão Competente"),
        ),
        migrations.AlterField(
            model_name="certificadoqsms",
            name="descricao",
            field=models.TextField(blank=True, null=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="certificadoqsms",
            name="link_orgao",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="Link do Órgão"
            ),
        ),
        migrations.AlterField(
            model_name="certificadoqsms",
            name="orgao_competente",
            field=models.CharField(max_length=255, verbose_name="Órgão Competente"),
        ),
        migrations.AlterField(
            model_name="checklist",
            name="aprovado",
            field=models.CharField(
                choices=[("Sim", "Sim"), ("Não", "Não")], max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="checklist",
            name="data_aprovacao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Aprovação/Realização"
            ),
        ),
        migrations.AlterField(
            model_name="condutorblacklist",
            name="motivo_reprovacao",
            field=models.TextField(verbose_name="Motivo da Reprovação"),
        ),
        migrations.AlterField(
            model_name="pgr",
            name="tipo_seguro",
            field=models.CharField(
                choices=[("Próprio", "Próprio"), ("DDR", "DDR")],
                max_length=10,
                verbose_name="Tipo de Seguro",
            ),
        ),
        migrations.AlterField(
            model_name="pgr",
            name="titulo_cliente",
            field=models.CharField(
                max_length=255, verbose_name="TÃ\xadtulo do PGR (Cliente)"
            ),
        ),
        migrations.AlterField(
            model_name="rotograma",
            name="nome_titulo",
            field=models.CharField(max_length=255, verbose_name="Nome/TÃ\xadtulo"),
        ),
        migrations.AlterField(
            model_name="seguro",
            name="apolice_pdf",
            field=models.FileField(
                upload_to="seguros/apolices/", verbose_name="Upload da Apólice (PDF)"
            ),
        ),
        migrations.AlterField(
            model_name="seguro",
            name="descricao_resumo",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descrição/Resumo"
            ),
        ),
        migrations.AlterField(
            model_name="seguro",
            name="tipo_apolice",
            field=models.CharField(max_length=100, verbose_name="Tipo de Apólice"),
        ),
        migrations.AlterField(
            model_name="seguro",
            name="vigencia",
            field=models.DateField(verbose_name="Vigência do Seguro"),
        ),
        migrations.AlterField(
            model_name="sinistro",
            name="seguradora_responsavel",
            field=models.CharField(
                max_length=100, verbose_name="Seguradora Responsável"
            ),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("Cavalo Mecânico", "Cavalo Mecânico"),
                    ("Carreta", "Carreta"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="veiculoassegurado",
            name="ano_fabricacao",
            field=models.IntegerField(verbose_name="Ano de Fabricação"),
        ),
        migrations.AlterField(
            model_name="veiculoassegurado",
            name="assistencia_km",
            field=models.IntegerField(verbose_name="Reboque/Assistência 24h (KM)"),
        ),
        migrations.AlterField(
            model_name="veiculoassegurado",
            name="vigencia",
            field=models.DateField(verbose_name="Vigência"),
        ),
    ]
