# Generated by Django 5.2.7 on 2026-01-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0013_modulepermissions_delete_moduleattachmentpermissions_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agendafarmaco",
            options={
                "ordering": ["data_evento", "hora_evento"],
                "verbose_name": "Evento da Agenda FÃ\x83Â¡rmaco",
                "verbose_name_plural": "Eventos da Agenda FÃ\x83Â¡rmaco",
            },
        ),
        migrations.AlterModelOptions(
            name="certificadofarmaco",
            options={
                "ordering": ["validade"],
                "verbose_name": "Certificado FÃ\x83Â¡rmaco",
                "verbose_name_plural": "Certificados FÃ\x83Â¡rmaco",
            },
        ),
        migrations.AlterModelOptions(
            name="farmacohistoricotarefa",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "HistÃ\x83Â³rico de Tarefa de FÃ\x83Â¡rmaco",
                "verbose_name_plural": "HistÃ\x83Â³ricos de Tarefas de FÃ\x83Â¡rmaco",
            },
        ),
        migrations.AlterModelOptions(
            name="farmacotarefa",
            options={
                "ordering": ["-criado_em"],
                "verbose_name": "Tarefa de FÃ\x83Â¡rmaco",
                "verbose_name_plural": "Tarefas de FÃ\x83Â¡rmaco",
            },
        ),
        migrations.AlterModelOptions(
            name="modulepermissions",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("view_gr_module", "Pode visualizar mÃ\x83Â³dulo GR"),
                    (
                        "view_gr_attachments",
                        "Pode visualizar anexos do GR (PGRs, Rotogramas)",
                    ),
                    ("view_security_module", "Pode visualizar mÃ\x83Â³dulo Security"),
                    (
                        "view_security_attachments",
                        "Pode visualizar anexos do Security (ApÃ\x83Â³lices, Certificados)",
                    ),
                    ("view_qsms_module", "Pode visualizar mÃ\x83Â³dulo QSMS"),
                    (
                        "view_qsms_attachments",
                        "Pode visualizar anexos do QSMS (Certificados)",
                    ),
                    (
                        "view_farmaco_module",
                        "Pode visualizar mÃ\x83Â³dulo FÃ\x83Â¡rmaco",
                    ),
                    (
                        "view_farmaco_attachments",
                        "Pode visualizar anexos do FÃ\x83Â¡rmaco (Certificados)",
                    ),
                    (
                        "view_arquivosdiversos_module",
                        "Pode visualizar mÃ\x83Â³dulo Arquivos Diversos",
                    ),
                    (
                        "view_all_arquivodiverso",
                        "Pode visualizar todos os arquivos diversos",
                    ),
                ),
                "verbose_name": "PermissÃ\x83Â£o de MÃ\x83Â³dulo",
                "verbose_name_plural": "PermissÃ\x83Âµes de MÃ\x83Â³dulos",
            },
        ),
        migrations.AlterModelOptions(
            name="qsmshistoricotarefa",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "HistÃ\x83Â³rico de Tarefa de QSMS",
                "verbose_name_plural": "HistÃ\x83Â³ricos de Tarefas de QSMS",
            },
        ),
        migrations.AlterModelOptions(
            name="securityhistoricotarefa",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "HistÃ\x83Â³rico de Tarefa de Security",
                "verbose_name_plural": "HistÃ\x83Â³ricos de Tarefas de Security",
            },
        ),
        migrations.AlterField(
            model_name="arquivodiverso",
            name="descricao",
            field=models.TextField(
                blank=True, null=True, verbose_name="DescriÃ\x83Â§Ã\x83Â£o do Documento"
            ),
        ),
        migrations.AlterField(
            model_name="arquivodiverso",
            name="titulo",
            field=models.CharField(max_length=255, verbose_name="TÃ\x83Â\xadtulo"),
        ),
        migrations.AlterField(
            model_name="certificadofarmaco",
            name="descricao",
            field=models.TextField(
                blank=True, null=True, verbose_name="DescriÃ\x83Â§Ã\x83Â£o"
            ),
        ),
        migrations.AlterField(
            model_name="certificadofarmaco",
            name="link_orgao",
            field=models.URLField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Link do Ã\x83â\x80\x9crgÃ\x83Â£o",
            ),
        ),
        migrations.AlterField(
            model_name="certificadofarmaco",
            name="orgao_competente",
            field=models.CharField(
                max_length=255, verbose_name="Ã\x83â\x80\x9crgÃ\x83Â£o Competente"
            ),
        ),
        migrations.AlterField(
            model_name="certificadoqsms",
            name="descricao",
            field=models.TextField(
                blank=True, null=True, verbose_name="DescriÃ\x83Â§Ã\x83Â£o"
            ),
        ),
        migrations.AlterField(
            model_name="certificadoqsms",
            name="link_orgao",
            field=models.URLField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Link do Ã\x83â\x80\x9crgÃ\x83Â£o",
            ),
        ),
        migrations.AlterField(
            model_name="certificadoqsms",
            name="orgao_competente",
            field=models.CharField(
                max_length=255, verbose_name="Ã\x83â\x80\x9crgÃ\x83Â£o Competente"
            ),
        ),
        migrations.AlterField(
            model_name="checklist",
            name="aprovado",
            field=models.CharField(
                choices=[("Sim", "Sim"), ("Nao", "Nao")], max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="checklist",
            name="data_aprovacao",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Data de AprovaÃ\x83Â§Ã\x83Â£o/RealizaÃ\x83Â§Ã\x83Â£o",
            ),
        ),
        migrations.AlterField(
            model_name="condutorblacklist",
            name="motivo_reprovacao",
            field=models.TextField(verbose_name="Motivo da ReprovaÃ\x83Â§Ã\x83Â£o"),
        ),
        migrations.AlterField(
            model_name="pgr",
            name="tipo_seguro",
            field=models.CharField(
                choices=[("PrÃ\x83Â³prio", "PrÃ\x83Â³prio"), ("DDR", "DDR")],
                max_length=10,
                verbose_name="Tipo de Seguro",
            ),
        ),
        migrations.AlterField(
            model_name="pgr",
            name="titulo_cliente",
            field=models.CharField(
                max_length=255, verbose_name="TÃ\x83Â\xadtulo do PGR (Cliente)"
            ),
        ),
        migrations.AlterField(
            model_name="rotograma",
            name="nome_titulo",
            field=models.CharField(max_length=255, verbose_name="Nome/TÃ\x83Â\xadtulo"),
        ),
        migrations.AlterField(
            model_name="seguro",
            name="apolice_pdf",
            field=models.FileField(
                upload_to="seguros/apolices/",
                verbose_name="Upload da ApÃ\x83Â³lice (PDF)",
            ),
        ),
        migrations.AlterField(
            model_name="seguro",
            name="descricao_resumo",
            field=models.TextField(
                blank=True, null=True, verbose_name="DescriÃ\x83Â§Ã\x83Â£o/Resumo"
            ),
        ),
        migrations.AlterField(
            model_name="seguro",
            name="tipo_apolice",
            field=models.CharField(
                max_length=100, verbose_name="Tipo de ApÃ\x83Â³lice"
            ),
        ),
        migrations.AlterField(
            model_name="seguro",
            name="vigencia",
            field=models.DateField(verbose_name="VigÃ\x83Âªncia do Seguro"),
        ),
        migrations.AlterField(
            model_name="sinistro",
            name="seguradora_responsavel",
            field=models.CharField(
                max_length=100, verbose_name="Seguradora ResponsÃ\x83Â¡vel"
            ),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("Cavalo Mecanico", "Cavalo Mecanico"),
                    ("Carreta", "Carreta"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="veiculoassegurado",
            name="ano_fabricacao",
            field=models.IntegerField(verbose_name="Ano de FabricaÃ\x83Â§Ã\x83Â£o"),
        ),
        migrations.AlterField(
            model_name="veiculoassegurado",
            name="assistencia_km",
            field=models.IntegerField(
                verbose_name="Reboque/AssistÃ\x83Âªncia 24h (KM)"
            ),
        ),
        migrations.AlterField(
            model_name="veiculoassegurado",
            name="vigencia",
            field=models.DateField(verbose_name="VigÃ\x83Âªncia"),
        ),
    ]
