# Generated by Django 5.2.7 on 2026-01-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0014_alter_agendafarmaco_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arquivodiverso",
            name="descricao",
            field=models.TextField(blank=True, null=True, verbose_name="Descricao"),
        ),
        migrations.AlterField(
            model_name="certificadofarmaco",
            name="descricao",
            field=models.TextField(blank=True, null=True, verbose_name="Descricao"),
        ),
        migrations.AlterField(
            model_name="certificadoqsms",
            name="descricao",
            field=models.TextField(blank=True, null=True, verbose_name="Descricao"),
        ),
        migrations.AlterField(
            model_name="checklist",
            name="data_aprovacao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Aprovacao/Realizacao"
            ),
        ),
        migrations.AlterField(
            model_name="checklist",
            name="data_fim_validade",
            field=models.DateField(blank=True, null=True, verbose_name="Validade"),
        ),
        migrations.AlterField(
            model_name="gerenciadorarisco",
            name="validade_checklist",
            field=models.IntegerField(
                choices=[(30, "30 dias"), (60, "60 dias"), (90, "90 dias")],
                verbose_name="Validade",
            ),
        ),
        migrations.AlterField(
            model_name="pgr",
            name="validade",
            field=models.DateField(verbose_name="Validade"),
        ),
        migrations.AlterField(
            model_name="seguro",
            name="descricao_resumo",
            field=models.TextField(blank=True, null=True, verbose_name="Descricao"),
        ),
        migrations.AlterField(
            model_name="seguro",
            name="vigencia",
            field=models.DateField(verbose_name="Vigencia"),
        ),
        migrations.AlterField(
            model_name="veiculoassegurado",
            name="vigencia",
            field=models.DateField(verbose_name="Vigencia"),
        ),
    ]
