# Generated by Django 5.2.7 on 2026-07-08 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0015_alter_arquivodiverso_descricao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulepermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': (('view_gr_module', 'Pode visualizar mÃ\x83³dulo GR'), ('view_gr_attachments', 'Pode visualizar anexos do GR (PGRs, Rotogramas)'), ('view_security_module', 'Pode visualizar módulo Security'), ('view_security_attachments', 'Pode visualizar anexos do Security (Apólices, Certificados)'), ('view_qsms_module', 'Pode visualizar módulo QSMS'), ('view_qsms_attachments', 'Pode visualizar anexos do QSMS (Certificados)'), ('view_farmaco_module', 'Pode visualizar módulo Fármaco'), ('view_farmaco_attachments', 'Pode visualizar anexos do Fármaco (Certificados)'), ('view_agregados_module', 'Pode visualizar módulo Documentação de Agregados'), ('view_agregados_attachments', 'Pode visualizar anexos de Agregados'), ('view_arquivosdiversos_module', 'Pode visualizar módulo Arquivos Diversos'), ('view_all_arquivodiverso', 'Pode visualizar todos os arquivos diversos')), 'verbose_name': 'Permissão de Módulo', 'verbose_name_plural': 'Permissões de Módulos'},
        ),
        migrations.CreateModel(
            name='DocumentacaoAgregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('condutor', models.CharField(max_length=255, verbose_name='Condutor Responsável')),
                ('crlv_ano', models.IntegerField(verbose_name='Ano em Exercício (CRLV)')),
                ('crlv_pdf', models.FileField(upload_to='qsms/agregados/crlv/', verbose_name='CRLV (PDF)')),
                ('dedetizacao_validade', models.DateField(blank=True, null=True, verbose_name='Validade da Dedetização')),
                ('dedetizacao_pdf', models.FileField(blank=True, null=True, upload_to='qsms/agregados/dedetizacao/', verbose_name='Comprovante de Dedetização (PDF)')),
                ('limpeza_validade', models.DateField(blank=True, null=True, verbose_name='Validade da Limpeza')),
                ('limpeza_pdf', models.FileField(blank=True, null=True, upload_to='qsms/agregados/limpeza/', verbose_name='Comprovante de Limpeza (PDF)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('responsavel_cadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agregados_cadastrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documentação de Agregado',
                'verbose_name_plural': 'Documentações de Agregados',
                'ordering': ['placa'],
            },
        ),
    ]
